import type { QuestionnaireDefinitionInput } from './schema.js';

/**
 * Cuestionario de ejemplo basado en el caso de uso de referencia.
 * Se usa para la carga inicial (seed) y en las pruebas. En producción,
 * cada proyecto configura el suyo desde el panel de administración.
 */
export const SAMPLE_QUESTIONNAIRE: QuestionnaireDefinitionInput = {
  schemaVersion: 1,
  title: 'Relevamiento nocturno — situación de calle',
  openingQuestion: 'que_ves',
  categories: [
    { key: 'personas', label: 'Personas' },
    { key: 'condiciones', label: 'Condiciones' },
    { key: 'pertenencias', label: 'Pertenencias' },
    { key: 'animales', label: 'Animales' },
  ],
  fields: [
    {
      key: 'personas',
      label: 'Personas',
      type: 'integer',
      category: 'personas',
      min: 0,
      max: 50,
      required: true,
      spoken: '{value} persona(s)',
      indicator: { aggregate: 'sum', label: 'Personas relevadas' },
    },
    {
      key: 'composicion',
      label: 'Composición',
      type: 'single_choice',
      category: 'personas',
      options: [
        { value: 'sola', label: 'persona sola' },
        { value: 'pareja', label: 'pareja' },
        { value: 'grupo_familiar', label: 'grupo familiar' },
        { value: 'grupo', label: 'grupo' },
      ],
      spoken: '{value}',
      indicator: { aggregate: 'distribution', label: 'Composición' },
    },
    {
      key: 'menores',
      label: 'Hay menores',
      type: 'boolean',
      category: 'personas',
      required: true,
      spoken: 'con menores',
      indicator: { aggregate: 'count_true', label: 'Relevamientos con menores' },
    },
    {
      key: 'menores_cantidad',
      label: 'Cantidad de menores',
      type: 'integer',
      category: 'personas',
      min: 1,
      max: 30,
      visibleIf: { field: 'menores', op: 'eq', value: true },
      required: true,
      spoken: '{value} menor(es)',
      indicator: { aggregate: 'sum', label: 'Menores relevados' },
    },
    { key: 'colchon', label: 'Colchón', type: 'boolean', category: 'condiciones', spoken: 'colchón' },
    { key: 'mantas', label: 'Mantas', type: 'integer', category: 'condiciones', min: 0, max: 30, spoken: '{value} manta(s)' },
    {
      key: 'pertenencias',
      label: 'Tiene pertenencias',
      type: 'boolean',
      category: 'pertenencias',
      required: true,
      confirm: false,
    },
    {
      key: 'pertenencias_tipo',
      label: 'Pertenencias',
      type: 'multi_choice',
      category: 'pertenencias',
      options: [
        { value: 'mochila', label: 'mochila' },
        { value: 'bolsos', label: 'bolsos' },
        { value: 'carro', label: 'carro' },
        { value: 'ropa', label: 'ropa' },
        { value: 'otros', label: 'otros' },
      ],
      visibleIf: { field: 'pertenencias', op: 'eq', value: true },
      requiredIf: { field: 'pertenencias', op: 'eq', value: true },
      spoken: '{value}',
      indicator: { aggregate: 'distribution', label: 'Pertenencias' },
    },
    {
      key: 'animales',
      label: 'Hay animales',
      type: 'boolean',
      category: 'animales',
      required: true,
      confirm: false,
      indicator: { aggregate: 'count_true', label: 'Relevamientos con animales' },
    },
    {
      key: 'animales_tipo',
      label: 'Animales',
      type: 'multi_choice',
      category: 'animales',
      options: [
        { value: 'perro', label: 'perro' },
        { value: 'gato', label: 'gato' },
        { value: 'otro', label: 'otro animal' },
      ],
      visibleIf: { field: 'animales', op: 'eq', value: true },
      requiredIf: { field: 'animales', op: 'eq', value: true },
      spoken: '{value}',
    },
    {
      key: 'animales_cantidad',
      label: 'Cantidad de animales',
      type: 'integer',
      category: 'animales',
      min: 1,
      max: 30,
      visibleIf: { field: 'animales', op: 'eq', value: true },
      confirm: false,
    },
    { key: 'observaciones', label: 'Observaciones', type: 'text', confirm: false },
  ],
  questions: [
    {
      key: 'que_ves',
      text: '¿Qué estás viendo?',
      fields: ['personas', 'composicion', 'menores', 'menores_cantidad', 'colchon', 'mantas', 'pertenencias', 'pertenencias_tipo', 'animales', 'animales_tipo', 'animales_cantidad', 'observaciones'],
    },
    { key: 'cuantas_personas', text: '¿Cuántas personas hay?', fields: ['personas', 'composicion'] },
    { key: 'menores', text: '¿Ves algún menor?', fields: ['menores', 'menores_cantidad'], followUps: ['menores_cuantos'] },
    {
      key: 'menores_cuantos',
      text: '¿Cuántos menores?',
      fields: ['menores_cantidad'],
      visibleIf: { field: 'menores', op: 'eq', value: true },
    },
    { key: 'pertenencias', text: '¿Tiene pertenencias?', fields: ['pertenencias', 'pertenencias_tipo'], followUps: ['pertenencias_cuales'] },
    {
      key: 'pertenencias_cuales',
      text: '¿Qué pertenencias tiene?',
      fields: ['pertenencias_tipo'],
      visibleIf: { field: 'pertenencias', op: 'eq', value: true },
    },
    { key: 'animales', text: '¿Hay algún animal?', fields: ['animales', 'animales_tipo', 'animales_cantidad'], followUps: ['animales_detalle'] },
    {
      key: 'animales_detalle',
      text: '¿Qué animal y cuántos?',
      fields: ['animales_tipo', 'animales_cantidad'],
      visibleIf: { field: 'animales', op: 'eq', value: true },
    },
  ],
  completion: { requireConfirmation: true },
};
